# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('idea_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
