# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_ideas_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.TextField(max_length=50)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='ideas',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ideacomment',
            name='idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daily.Ideas'),
        ),
        migrations.AddField(
            model_name='ideacategory',
            name='idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='daily.Ideas'),
        ),
    ]
