# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20161105_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile1',
            new_name='Profile',
        ),
    ]
